apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-enterprise-operator
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-enterprise-operator
  template:
    metadata:
      labels:
        name: redis-enterprise-operator
    spec:
      imagePullSecrets:
        - name: dockerhub-secrets
      serviceAccountName: redis-enterprise-operator
      containers:
        - name: redis-enterprise-operator
          # Replace this with the built image name
          image: redislabs/operator-internal:100.0.0-500
          command:
          - redis-enterprise-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "redis-enterprise-operator"
            - name: DATABASE_CONTROLLER_ENABLED
              value: "true"
            - name: REDB_NAMESPACES
              value: "team1,team2"
          resources:
            limits:
              cpu: 4000m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi
