---
apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: "redis-enterprise"
  namespace: redis
spec:
  nodes: 3
  pullSecrets:
    - name: dockerhub-secret
  redisEnterpriseImageSpec:
    imagePullPolicy:  IfNotPresent
    repository: redislabs/redis-internal
  redisEnterpriseServicesRiggerImageSpec:
    imagePullPolicy:  IfNotPresent
    repository:       redislabs/k8s-controller-internal
  bootstrapperImageSpec:
    imagePullPolicy:  IfNotPresent
    repository:       redislabs/operator-internal
