---
apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: "redis-enterprise"
  namespace: redis
spec:
  nodes: 3
  pullSecrets:
    - name: dockerhub-secret
  redisEnterpriseImageSpec:
    repository: redislabs/redis
